# OpenTelemetry Collector — client-side trace forwarding
# Generated by scripts/onboard_client.sh — do not edit manually.
#
# Receives OTLP traces from local applications, adds the client label,
# and exports them to the central Tempo instance via Nginx.

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 5s

  # Inject client label as a resource attribute on every span
  resource:
    attributes:
      - key:    client
        value:  "{{CLIENT_NAME}}"
        action: upsert

exporters:
  otlphttp:
    endpoint: "http://{{STACK_HOST}}:{{STACK_PORT}}"
    auth:
      authenticator: basicauth
    headers:
      # Nginx injects X-Scope-OrgID from the basic auth username,
      # but we set it here as well for direct-to-Tempo scenarios.
      X-Scope-OrgID: "{{CLIENT_NAME}}"

extensions:
  basicauth:
    client_auth:
      username: "{{CLIENT_NAME}}"
      password: "{{CLIENT_PASSWORD}}"

service:
  extensions: [basicauth]
  pipelines:
    traces:
      receivers:  [otlp]
      processors: [resource, batch]
      exporters:  [otlphttp]
