# Promtail — client-side log shipping
# Generated by scripts/onboard_client.sh — do not edit manually.
#
# Pushes logs to the central Loki instance via Nginx.
# Tenant is identified by the basic auth username (client name).

server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: "http://{{STACK_HOST}}:{{STACK_PORT}}/loki/api/v1/push"
    basic_auth:
      username: "{{CLIENT_NAME}}"
      password: "{{CLIENT_PASSWORD}}"
    external_labels:
      client: "{{CLIENT_NAME}}"

scrape_configs:

  # System journal logs
  - job_name: journal
    journal:
      max_age: 12h
      labels:
        job:    systemd
        client: "{{CLIENT_NAME}}"
    relabel_configs:
      - source_labels: [__journal__systemd_unit]
        target_label:  unit

  # Syslog / auth log
  - job_name: syslog
    static_configs:
      - targets: [localhost]
        labels:
          job:       syslog
          client:    "{{CLIENT_NAME}}"
          __path__:  /var/log/syslog

  # Auth log
  - job_name: auth
    static_configs:
      - targets: [localhost]
        labels:
          job:      auth
          client:   "{{CLIENT_NAME}}"
          __path__: /var/log/auth.log

  # Nginx access/error logs (if Nginx runs on the client)
  - job_name: nginx
    static_configs:
      - targets: [localhost]
        labels:
          job:      nginx
          client:   "{{CLIENT_NAME}}"
          __path__: /var/log/nginx/*.log
