# Prometheus agent — client-side metrics collection
# Generated by scripts/onboard_client.sh — do not edit manually.
#
# Runs in agent mode (remote_write only, no local TSDB).
# All metrics are labeled with client="{{CLIENT_NAME}}".

global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    client: "{{CLIENT_NAME}}"

remote_write:
  - url: "http://{{STACK_HOST}}:{{STACK_PORT}}/api/v1/push"
    basic_auth:
      username: "{{CLIENT_NAME}}"
      password: "{{CLIENT_PASSWORD}}"
    queue_config:
      max_samples_per_send: 1000
      max_shards: 10
      capacity: 2500

scrape_configs:

  # Node / OS metrics (requires node_exporter running on the client)
  - job_name: node
    static_configs:
      - targets: ["localhost:9100"]

  # Optional: scrape additional exporters below
  # - job_name: my-app
  #   static_configs:
  #     - targets: ["localhost:8080"]
  #   metrics_path: /metrics
